wandb_version: 1

batch_size:
  desc: null
  value: 8
learning_rate:
  desc: null
  value: 0.001
weight_decay:
  desc: null
  value: 0.0001
epochs:
  desc: null
  value: 50
patience:
  desc: null
  value: 50
step_size:
  desc: null
  value: 5
gamma:
  desc: null
  value: 0.1
dropout:
  desc: null
  value: 0.5
dataset:
  desc: null
  value: appledataset
_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1718333165
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.8.19
      5: 0.17.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
